export const cards = [
  //template for the cards
  // {
  //   id: 0,
  //   cardType: "",
  //   cardCategory: "",
  //   cardName: "",
  //   uprightPoints: [],
  //   reversedPoints: [],
  // },
  {
    id: 1,
    cardType: "Minor Arcana",
    cardCategory: "Cups",
    cardName: "Ace of Cups",
    uprightPoints: [
      "love",
      "new feelings",
      "emotional awakening",
      "creativity",
      "spirituality",
      "intuition",
    ],
    reversedPoints: [
      "coldness",
      "emptiness",
      "emotional loss",
      "blocked creativity",
      "feeling unloved",
      "gloominess",
    ],
  },
  {
    id: 2,
    cardType: "Minor Arcana",
    cardCategory: "Cups",
    cardName: "2 of Cups",
    uprightPoints: [
      "unity",
      "partnership",
      "attraction",
      "connection",
      "close bonds",
      "joining forces",
      "mutual respect",
    ],
    reversedPoints: [
      "separation",
      "rejection",
      "division",
      "imbalance",
      "tension",
      "bad communication",
      "withdrawal",
    ],
  },
  {
    id: 3,
    cardType: "Minor Arcana",
    cardCategory: "Cups",
    cardName: "3 of Cups",
    uprightPoints: [
      "friendship",
      "community",
      "gatherings",
      "celebrations",
      "group events",
      "social events",
    ],
    reversedPoints: [
      "gossip",
      "scandal",
      "excess",
      "isolation",
      "loneliness",
      "solitude",
      "imbalanced social life",
    ],
  },
  {
    id: 4,
    cardType: "Minor Arcana",
    cardCategory: "Cups",
    cardName: "4 of Cups",
    uprightPoints: [
      "apathy",
      "contemplation",
      "feeling disconnected",
      "melancholy",
      "boredom",
      "indifference",
      "discontent",
    ],
    reversedPoints: [
      "clarity",
      "awareness",
      "acceptance",
      "choosing happiness",
      "depression",
      "negativity",
    ],
  },
  {
    id: 5,
    cardType: "Minor Arcana",
    cardCategory: "Cups",
    cardName: "5 of Cups",
    uprightPoints: [
      "loss",
      "grief",
      "disappointment",
      "sadness",
      "mourning",
      "discontent",
      "feeling let down",
    ],
    reversedPoints: [
      "acceptance",
      "moving on",
      "finding peace",
      "contentment",
      "seeing positives",
    ],
  },
  {
    id: 6,
    cardType: "Minor Arcana",
    cardCategory: "Cups",
    cardName: "6 of Cups",
    uprightPoints: [
      "nostalgia",
      "memories",
      "familiarity",
      "healing",
      "comfort",
      "sentimentality",
      "pleasure",
    ],
    reversedPoints: [
      "stuck in past",
      "moving forward",
      "leaving home",
      "independence",
    ],
  },
  {
    id: 7,
    cardType: "Minor Arcana",
    cardCategory: "Cups",
    cardName: "7 of Cups",
    uprightPoints: [
      "choices",
      "searching for purpose",
      "illusion",
      "fantasy",
      " daydreaming",
      "wishful thinking",
      "indecision",
    ],
    reversedPoints: [
      "lack of purpose",
      "disarray",
      "confusion",
      "diversion",
      "distractions",
      "clarity",
      "making choices",
    ],
  },
  {
    id: 8,
    cardType: "Minor Arcana",
    cardCategory: "Cups",
    cardName: "8 of Cups",
    uprightPoints: [
      "abandonment",
      "walking away",
      "letting go",
      "searching for truth",
      "leaving behind",
    ],
    reversedPoints: [
      "stagnation",
      "monotony",
      "accepting less",
      "avoidance",
      "fear of change",
      "staying in bad situation",
    ],
  },
  {
    id: 9,
    cardType: "Minor Arcana",
    cardCategory: "Cups",
    cardName: "9 of Cups",
    uprightPoints: [
      "wishes coming true",
      "contentment",
      "satisfaction",
      "success",
      "achievements",
      "recognition",
      "pleasure",
    ],
    reversedPoints: [
      "unhappiness",
      "lack of fulfillment",
      "disappointment",
      "underachievement",
      "arrogance",
      "snobbery",
    ],
  },
  {
    id: 10,
    cardType: "Minor Arcana",
    cardCategory: "Cups",
    cardName: "10 of Cups",
    uprightPoints: [
      "happiness",
      "homecomings",
      "fulfillment",
      "emotional stability",
      "security",
      "domestic harmony",
    ],
    reversedPoints: [
      "unhappy home",
      "separation",
      "domestic conflict",
      "disharmony",
      "isolation",
    ],
  },
  {
    id: 11,
    cardType: "Minor Arcana",
    cardCategory: "Cups",
    cardName: "Page of Cups",
    uprightPoints: [
      "idealism",
      "sensitivity",
      "dreamer",
      "naivete",
      "innocence",
      "inner child",
      "head in the clouds",
    ],
    reversedPoints: [
      "emotional vulnerability",
      "immaturity",
      "neglecting inner child",
      "escapism",
      "insecurity",
    ],
  },
  {
    id: 12,
    cardType: "Minor Arcana",
    cardCategory: "Cups",
    cardName: "Knight of Cups",
    uprightPoints: [
      "idealist",
      "charming",
      "artistic",
      "graceful",
      "tactful",
      "diplomatic",
      "mediator",
      "negotiator",
    ],
    reversedPoints: [
      "disappointment",
      "tantrums",
      "moodiness",
      "turmoil",
      "avoiding conflict",
      "vanity",
    ],
  },
  {
    id: 13,
    cardType: "Minor Arcana",
    cardCategory: "Cups",
    cardName: "Queen of Cups",
    uprightPoints: [
      "compassion",
      "warmth",
      "kindness",
      "intuition",
      "healer",
      "counsellor",
      "supportive",
    ],
    reversedPoints: [
      "insecurity",
      "giving too much",
      "overly-sensitive",
      "needy",
      "fragile",
      "dependence",
      "martyrdom",
    ],
  },
  {
    id: 14,
    cardType: "Minor Arcana",
    cardCategory: "Cups",
    cardName: "King of Cups",
    uprightPoints: [
      "wise",
      "diplomatic",
      "balance between head and heart",
      "devoted",
      "advisor",
      "counsellor",
    ],
    reversedPoints: [
      "overwhelmed",
      "anxious",
      "cold",
      "repressed",
      "withdrawn",
      "manipulative",
      "selfish",
    ],
  },
  {
    id: 15,
    cardType: "Minor Arcana",
    cardCategory: "Wands",
    cardName: "Ace of Wands",
    uprightPoints: [
      "inspiration",
      "creative spark",
      "new initiative",
      "new passion",
      "enthusiasm",
      "energy",
    ],
    reversedPoints: [
      "delays",
      "blocks",
      "lack of passion",
      "lack of energy",
      "hesitancy",
      "creative blocks",
    ],
  },
  {
    id: 16,
    cardType: "Minor Arcana",
    cardCategory: "Wands",
    cardName: "2 of Wands",
    uprightPoints: [
      "planning",
      "first steps",
      "making decisions",
      "leaving comfort",
      "taking risks",
    ],
    reversedPoints: [
      "bad planning",
      "overanalyzing",
      "not taking action",
      "playing it safe",
      "avoiding risk",
    ],
  },
  {
    id: 17,
    cardType: "Minor Arcana",
    cardCategory: "Wands",
    cardName: "3 of Wands",
    uprightPoints: [
      "momentum",
      "confidence",
      "expansion",
      "growth",
      "foresight",
      "looking ahead",
    ],
    reversedPoints: [
      "restriction",
      "limitations",
      "lack of progress",
      "obstacles",
      "delays",
      "frustration",
    ],
  },
  {
    id: 18,
    cardType: "Minor Arcana",
    cardCategory: "Wands",
    cardName: "4 of Wands",
    uprightPoints: [
      "community",
      "home",
      "celebrations",
      "reunions",
      "parties",
      "gatherings",
      "stability",
      "belonging",
    ],
    reversedPoints: [
      "lack of support",
      "instability",
      "feeling unwelcome",
      "transience",
      "lack of roots",
      "home conflict",
    ],
  },
  {
    id: 19,
    cardType: "Minor Arcana",
    cardCategory: "Wands",
    cardName: "5 of Wands",
    uprightPoints: [
      "conflict",
      "competition",
      "arguments",
      "aggression",
      "tension",
      "rivals",
      "clashes of ego",
    ],
    reversedPoints: [
      "end of conflict",
      "cooperation",
      "agreements",
      "truces",
      "harmony",
      "peace",
      "avoiding conflict",
    ],
  },
  {
    id: 20,
    cardType: "Minor Arcana",
    cardCategory: "Wands",
    cardName: "6 of Wands",
    uprightPoints: [
      "success",
      "victory",
      "triumph",
      "rewards",
      "recognition",
      "praise",
      "acclaim",
      "pride",
    ],
    reversedPoints: [
      "failure",
      "lack of recognition",
      "no rewards",
      "lack of achievement",
    ],
  },
  {
    id: 21,
    cardType: "Minor Arcana",
    cardCategory: "Wands",
    cardName: "7 of Wands",
    uprightPoints: [
      "protectiveness",
      "standing up for yourself",
      "defending yourself",
      "protecting territory",
    ],
    reversedPoints: [
      "giving up",
      " admitting defeat",
      "yielding",
      "lack of self belief",
      "surrender",
    ],
  },
  {
    id: 22,
    cardType: "Minor Arcana",
    cardCategory: "Wands",
    cardName: "8 of Wands",
    uprightPoints: [
      "movement",
      "speed",
      "progress",
      "quick decisions",
      "sudden changes",
      "excitement",
    ],
    reversedPoints: [
      "waiting",
      "slowness",
      "chaos",
      "delays",
      "losing momentum",
      "hastiness",
      "being unprepared",
    ],
  },
  {
    id: 23,
    cardType: "Minor Arcana",
    cardCategory: "Wands",
    cardName: "9 of Wands",
    uprightPoints: [
      "last stand",
      "persistence",
      "grit",
      "resilience",
      "perseverance",
      "close to success",
      "fatigue",
    ],
    reversedPoints: [
      "stubbornness",
      "rigidity",
      "defensiveness",
      "refusing compromise",
      "giving up",
    ],
  },
  {
    id: 24,
    cardType: "Minor Arcana",
    cardCategory: "Wands",
    cardName: "10 of Wands",
    uprightPoints: [
      "burden",
      "responsibility",
      "duty",
      "stress",
      "obligation",
      "burning out",
      "struggles",
    ],
    reversedPoints: [
      "failure to delegate",
      "shouldering too much responsibility",
      "collapse",
      "breakdown",
    ],
  },
  {
    id: 25,
    cardType: "Minor Arcana",
    cardCategory: "Wands",
    cardName: "Page of Wands",
    uprightPoints: [
      "adventure",
      "excitement",
      "fresh ideas",
      "cheerfulness",
      "energetic",
      "fearless",
      "extroverted",
    ],
    reversedPoints: [
      "hasty",
      "impatient",
      "lacking ideas",
      "tantrums",
      "laziness",
      "boring",
      "unreliable",
      "distracted",
    ],
  },
  {
    id: 26,
    cardType: "Minor Arcana",
    cardCategory: "Wands",
    cardName: "Knight of Wands",
    uprightPoints: [
      "courageous",
      "energetic",
      "charming",
      "hero",
      "rebellious",
      "hot tempered",
      "free spirit",
    ],
    reversedPoints: [
      "arrogant",
      "reckless",
      "impatient",
      "lack of self control",
      "passive",
      "volatile",
      "domineering",
    ],
  },
  {
    id: 27,
    cardType: "Minor Arcana",
    cardCategory: "Wands",
    cardName: "Queen of Wands",
    uprightPoints: [
      "confident",
      "self - assured",
      "passionate",
      "determined",
      "social",
      "charismatic",
      "vivacious",
      "optimistic",
    ],
    reversedPoints: [
      "demanding",
      "vengeful",
      "low confidence",
      "jealous",
      "selfish",
      "temperamental",
      "bully",
    ],
  },
  {
    id: 28,
    cardType: "Minor Arcana",
    cardCategory: "Wands",
    cardName: "King of Wands",
    uprightPoints: [
      "leadership",
      "vision",
      "big picture",
      "taking control",
      "daring decisions",
      "boldness",
      "optimism",
    ],
    reversedPoints: [
      "forceful",
      "domineering",
      "tyrant",
      "vicious",
      "powerless",
      "ineffective",
      "weak leader",
    ],
  },
  {
    id: 29,
    cardType: "Minor Arcana",
    cardCategory: "Swords",
    cardName: "Ace of Swords",
    uprightPoints: [
      "clarity",
      "breakthrough",
      "new idea",
      "concentration",
      "vision",
      "force",
      "focus",
      "truth",
    ],
    reversedPoints: [
      "confusion",
      "miscommunication",
      "hostility",
      "arguments",
      "destruction",
      "brutality",
    ],
  },
  {
    id: 30,
    cardType: "Minor Arcana",
    cardCategory: "Swords",
    cardName: "2 of Swords",
    uprightPoints: [
      "stalemate",
      "difficult choices",
      "stuck in the middle",
      "denial",
      "hidden information",
    ],
    reversedPoints: [
      "indecision",
      "hesitancy",
      "anxiety",
      "too much information",
      "no right choice",
      "truth revealed",
    ],
  },
  {
    id: 31,
    cardType: "Minor Arcana",
    cardCategory: "Swords",
    cardName: "3 of Swords",
    uprightPoints: [
      "heartbreak",
      "separation",
      "sadness",
      "grief",
      "sorrow",
      "upset",
      "loss",
      "trauma",
      "tears",
    ],
    reversedPoints: [
      "healing",
      "forgiveness",
      "recovery",
      "reconciliation",
      "repressing emotions",
    ],
  },
  {
    id: 32,
    cardType: "Minor Arcana",
    cardCategory: "Swords",
    cardName: "4 of Swords",
    uprightPoints: [
      "rest",
      "relaxation",
      "peace",
      "sanctuary",
      "recuperation",
      "self - protection",
      "rejuvenation",
    ],
    reversedPoints: [
      "recovery",
      "awakening",
      "re-entering world",
      "release from isolation",
      "restlessness",
      "burnout",
    ],
  },
  {
    id: 33,
    cardType: "Minor Arcana",
    cardCategory: "Swords",
    cardName: "5 of Swords",
    uprightPoints: [
      "arguments",
      "disputes",
      "aggression",
      "bullying",
      "intimidation",
      "conflict",
      "hostility",
      "stress",
    ],
    reversedPoints: [
      "reconciliation",
      "resolution",
      "compromise",
      "revenge",
      "regret",
      "remorse",
      "cutting losses",
    ],
  },
  {
    id: 34,
    cardType: "Minor Arcana",
    cardCategory: "Swords",
    cardName: "6 of Swords",
    uprightPoints: [
      "moving on",
      "departure",
      "leaving behind",
      "distance",
      "accepting lessons",
    ],
    reversedPoints: [
      "stuck in past",
      "returning to trouble",
      "running away from problems",
      "trapped",
    ],
  },
  {
    id: 35,
    cardType: "Minor Arcana",
    cardCategory: "Swords",
    cardName: "7 of Swords",
    uprightPoints: [
      "lies",
      "trickery",
      "scheming",
      "strategy",
      "resourcefulness",
      "sneakiness",
      "cunning",
    ],
    reversedPoints: [
      "confession",
      "conscience",
      "regret",
      "maliciousness",
      "truth revealed",
    ],
  },
  {
    id: 36,
    cardType: "Minor Arcana",
    cardCategory: "Swords",
    cardName: "8 of Swords",
    uprightPoints: [
      "trapped",
      "restricted",
      "victimised",
      "paralysed",
      "helpless",
      "powerless",
      "imprisonment",
    ],
    reversedPoints: [
      "freedom",
      "release",
      "taking control",
      "survivor",
      "facing fears",
      "empowered",
      "surrender",
    ],
  },
  {
    id: 37,
    cardType: "Minor Arcana",
    cardCategory: "Swords",
    cardName: "9 of Swords",
    uprightPoints: [
      "fear",
      "anxiety",
      "negativity",
      "breaking point",
      "despair",
      "nightmares",
      "isolation",
    ],
    reversedPoints: [
      "recovery",
      "learning to cope",
      "facing life",
      "finding help",
      "shame",
      "guilt",
      "mental health issues",
    ],
  },
  {
    id: 38,
    cardType: "Minor Arcana",
    cardCategory: "Swords",
    cardName: "10 of Swords",
    uprightPoints: [
      "ruin",
      "failure",
      "bitterness",
      "collapse",
      "exhaustion",
      "dead end",
      "victimization",
      "betrayal",
    ],
    reversedPoints: [
      "survival",
      "improvement",
      "healing",
      "lessons learned",
      "despair",
      "relapse",
    ],
  },
  {
    id: 39,
    cardType: "Minor Arcana",
    cardCategory: "Swords",
    cardName: "Page of Swords",
    uprightPoints: [
      "curious",
      "witty",
      "chatty",
      "communicative",
      "inspired",
      "vigilant",
      "alert",
      "mental agility",
    ],
    reversedPoints: [
      "scatterbrained",
      "cynical",
      "sarcastic",
      "gossipy",
      "insulting",
      "rude",
      "lack of planning",
    ],
  },
  {
    id: 40,
    cardType: "Minor Arcana",
    cardCategory: "Swords",
    cardName: "Knight of Swords",
    uprightPoints: [
      "assertive",
      "direct",
      "impatient",
      "intellectual",
      "daring",
      "focused",
      "perfectionist",
      "ambitious",
    ],
    reversedPoints: [
      "rude",
      "tactless",
      "forceful",
      "bully",
      "aggressive",
      "vicious",
      "ruthless",
      "arrogant",
    ],
  },
  {
    id: 41,
    cardType: "Minor Arcana",
    cardCategory: "Swords",
    cardName: "Queen of Swords",
    uprightPoints: [
      "honest",
      "independent",
      "principled",
      "fair",
      "constructive criticism",
      "objective",
      "perceptive",
    ],
    reversedPoints: [
      "pessimistic",
      "malicious",
      "manipulative",
      "harsh",
      "bitter",
      "spiteful",
      "cruel",
      "deceitful",
      "unforgiving",
    ],
  },
  {
    id: 42,
    cardType: "Minor Arcana",
    cardCategory: "Swords",
    cardName: "King of Swords",
    uprightPoints: [
      "reason",
      "authority",
      "discipline",
      "integrity",
      "morality",
      "serious",
      "high standards",
      "strict",
    ],
    reversedPoints: [
      "irrational",
      "dictator",
      "oppressive",
      "inhumane",
      "controlling",
      "cold",
      "ruthless",
      "dishonest",
    ],
  },
  {
    id: 43,
    cardType: "Minor Arcana",
    cardCategory: "Pentacles",
    cardName: "Ace of Pentacles",
    uprightPoints: [
      "new opportunities",
      "resources",
      "abundance",
      "prosperity",
      "security",
      "stability",
      "manifestation",
    ],
    reversedPoints: [
      "missed chances",
      "scarcity",
      "deficiency",
      "instability",
      "stinginess",
      "bad investments",
    ],
  },
  {
    id: 44,
    cardType: "Minor Arcana",
    cardCategory: "Pentacles",
    cardName: "2 of Pentacles",
    uprightPoints: [
      "balancing resources",
      "adaptation",
      "resourcefulness",
      "flexibility",
      "stretching resources",
    ],
    reversedPoints: [
      "imbalance",
      "unorganized",
      "overwhelmed",
      "messiness",
      "chaos",
      "overextending",
    ],
  },
  {
    id: 45,
    cardType: "Minor Arcana",
    cardCategory: "Pentacles",
    cardName: "3 of Pentacles",
    uprightPoints: [
      "teamwork",
      "shared goals",
      "collaboration",
      "apprenticeship",
      "effort",
      "pooling energy",
    ],
    reversedPoints: [
      "lack of cohesion",
      "lack of teamwork",
      "apathy",
      "poor motivation",
      "conflict",
      "ego",
      "competition",
    ],
  },
  {
    id: 46,
    cardType: "Minor Arcana",
    cardCategory: "Pentacles",
    cardName: "4 of Pentacles",
    uprightPoints: [
      "possessiveness",
      "insecurity",
      "hoarding",
      "stinginess",
      "stability",
      "security",
      "savings",
      "materialism",
      "wealth",
      "frugality",
      "boundaries",
      "guardedness",
    ],
    reversedPoints: [
      "generosity",
      "giving",
      "spending",
      "openness",
      "financial insecurity",
      "reckless spending",
    ],
  },
  {
    id: 47,
    cardType: "Minor Arcana",
    cardCategory: "Pentacles",
    cardName: "5 of Pentacles",
    uprightPoints: [
      "hardship",
      "loss",
      "isolation",
      "feeling abandoned",
      "adversity",
      "struggle",
      "unemployment",
      "alienation",
      "disgrace",
    ],
    reversedPoints: [
      "positive changes",
      "recovery from loss",
      "overcoming adversity",
      "forgiveness",
      "feeling welcomed",
    ],
  },
  {
    id: 48,
    cardType: "Minor Arcana",
    cardCategory: "Pentacles",
    cardName: "6 of Pentacles",
    uprightPoints: [
      "generosity",
      "charity",
      "community",
      "material help",
      "support",
      "sharing",
      "giving and receiving",
      "gratitude",
    ],
    reversedPoints: [
      "power dynamics",
      "abuse of generosity",
      "strings attached gifts",
      "inequality",
      "extortion",
    ],
  },
  {
    id: 49,
    cardType: "Minor Arcana",
    cardCategory: "Pentacles",
    cardName: "7 of Pentacles",
    uprightPoints: [
      "harvest",
      "rewards",
      "results",
      "growth",
      "progress",
      "perseverance",
      "patience",
      "planning",
    ],
    reversedPoints: [
      "unfinished work",
      "procrastination",
      "low effort",
      "waste",
      "lack of growth",
      "setbacks",
      "impatience",
      "lack of reward",
    ],
  },
  {
    id: 50,
    cardType: "Minor Arcana",
    cardCategory: "Pentacles",
    cardName: "8 of Pentacles",
    uprightPoints: [
      "skill",
      "talent",
      "craftsmanship",
      "quality",
      "high standards",
      "expertise",
      "mastery",
      "commitment",
      "dedication",
      "accomplishment",
    ],
    reversedPoints: [
      "lack of quality",
      "rushed job",
      "bad reputation",
      "lack of motivation",
      "mediocrity",
      "laziness",
      "low skill",
      "dead-end job",
    ],
  },
  {
    id: 51,
    cardType: "Minor Arcana",
    cardCategory: "Pentacles",
    cardName: "9 of Pentacles",
    uprightPoints: [
      "rewarded efforts",
      "success",
      "achievement",
      "independence",
      "leisure",
      "material security",
      "self-sufficiency",
    ],
    reversedPoints: [
      "being guarded",
      "living beyond means",
      "material instability",
      "reckless spending",
      "superficiality",
    ],
  },
  {
    id: 52,
    cardType: "Minor Arcana",
    cardCategory: "Pentacles",
    cardName: "10 of Pentacles",
    uprightPoints: [
      "legacy",
      "roots",
      "family",
      "ancestry",
      "inheritance",
      "windfall",
      "foundations",
      "privilege",
      "affluence",
      "stability",
      "tradition",
    ],
    reversedPoints: [
      "family disputes",
      "bankruptcy",
      "debt",
      "fleeting success",
      "conflict over money",
      "instability",
      "breaking traditions",
    ],
  },
  {
    id: 53,
    cardType: "Minor Arcana",
    cardCategory: "Pentacles",
    cardName: "Page of Pentacles",
    uprightPoints: [
      "ambitious",
      "diligent",
      "goal oriented",
      "planner",
      "consistent",
      "star student",
      "studious",
      "grounded",
      "loyal",
      "faithful",
      "dependable",
    ],
    reversedPoints: [
      "foolish",
      "immature",
      "irresponsible",
      "lazy",
      "underachiever",
      "procrastinator",
      "missed chances",
      "poor prospects",
    ],
  },
  {
    id: 54,
    cardType: "Minor Arcana",
    cardCategory: "Pentacles",
    cardName: "Knight of Pentacles",
    uprightPoints: [
      "practical",
      "reliable",
      "efficient",
      "stoic",
      "slow and steady",
      "hard-working",
      "committed",
      "patient",
      "conservative",
    ],
    reversedPoints: [
      "workaholic",
      "laziness",
      "dull",
      "boring",
      "no initiative",
      "cheap",
      "irresponsible",
      "gambler",
      "risky investments",
    ],
  },
  {
    id: 55,
    cardType: "Minor Arcana",
    cardCategory: "Pentacles",
    cardName: "Queen of Pentacles",
    uprightPoints: [
      "generous",
      "caring",
      "nurturing",
      "homebody",
      "good business sense",
      "practical",
      "comforting",
      "welcoming",
      "sensible",
      "luxurious",
    ],
    reversedPoints: [
      "selfish",
      "unkempt",
      "jealous",
      "insecure",
      "greedy",
      "materialistic",
      "gold digger",
      "intolerant",
      "self-absorbed",
      "envious",
    ],
  },
  {
    id: 56,
    cardType: "Minor Arcana",
    cardCategory: "Pentacles",
    cardName: "King of Pentacles",
    uprightPoints: [
      "abundance",
      "prosperity",
      "security",
      "ambitious",
      "safe",
      "kind",
      "patriarchal",
      "protective",
      "businessman",
      "provider",
      "sensual",
      "reliable",
    ],
    reversedPoints: [
      "greed",
      "materialistic",
      "wasteful",
      "chauvinist",
      "poor financial decisions",
      "gambler",
      "exploitative",
      "possessive",
    ],
  },
  {
    id: 57,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "The Fool",
    uprightPoints: [
      "beginnings",
      "freedom",
      "innocence",
      "originality",
      "adventure",
      "idealism",
      "spontaneity",
    ],
    reversedPoints: [
      "reckless",
      "careless",
      "distracted",
      "naive",
      "foolish",
      "gullible",
      "stale",
      "dull",
    ],
  },
  {
    id: 58,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "The Magician",
    uprightPoints: [
      "willpower",
      "desire",
      "being resourceful",
      "skill",
      "ability",
      "concentration",
      "manifestation",
    ],
    reversedPoints: [
      "manipulation",
      "cunning",
      "trickery",
      "wasted talent",
      "illusion",
      "deception",
    ],
  },
  {
    id: 59,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "The High Priestess",
    uprightPoints: [
      "unconscious",
      "intuition",
      "mystery",
      "spirituality",
      "higher power",
      "inner voice",
    ],
    reversedPoints: [
      "repressed intuition",
      "hidden motives",
      "superficiality",
      "confusion",
      "cognitive dissonance",
    ],
  },
  {
    id: 60,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "The Empress",
    uprightPoints: [
      "divine feminine",
      "sensuality",
      "fertility",
      "nurturing",
      "creativity",
      "beauty",
      "abundance",
      "nature",
    ],
    reversedPoints: [
      "insecurity",
      "overbearing",
      "negligence",
      "smothering",
      "lack of growth",
      "lack of progress",
    ],
  },
  {
    id: 61,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "The Emperor",
    uprightPoints: [
      "stability",
      "structure",
      "protection",
      "authority",
      "control",
      "practicality",
      "focus",
      "discipline",
    ],
    reversedPoints: [
      "tyrant",
      "domineering",
      "rigid",
      "stubborn",
      "lack of discipline",
      "recklessness",
    ],
  },
  {
    id: 62,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "The Hierophant",
    uprightPoints: [
      "tradition",
      "social groups",
      "conventionality",
      "conformity",
      "education",
      "knowledge",
      "beliefs",
    ],
    reversedPoints: [
      "rebellion",
      "unconventionality",
      "non-conformity",
      "new methods",
      "ignorance",
    ],
  },
  {
    id: 63,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "",
    uprightPoints: [],
    reversedPoints: [],
  },
  {
    id: 64,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "The Lovers",
    uprightPoints: [
      "love",
      "unions",
      "partnerships",
      "relationships",
      "choices",
      "romance",
      "balance",
      "unity",
    ],
    reversedPoints: [
      "disharmony",
      "imbalance",
      "conflict",
      "detachment",
      "bad choices",
      "indecision",
    ],
  },
  {
    id: 65,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "The Chariot",
    uprightPoints: [
      "success",
      "ambition",
      "determination",
      "willpower",
      "control",
      "self - discipline",
      "focus",
    ],
    reversedPoints: [
      "forceful",
      "no direction",
      "no control",
      "powerless",
      "aggression",
      "obstacles",
    ],
  },
  {
    id: 66,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "Strength",
    uprightPoints: [
      "courage",
      "bravery",
      "confidence",
      "compassion",
      "self-confidence",
      "inner power",
    ],
    reversedPoints: [
      "self-doubt",
      "weakness",
      "low confidence",
      "inadequacy",
      "cowardice",
      "forcefulness",
    ],
  },
  {
    id: 67,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "The Hermit",
    uprightPoints: [
      "self-reflection",
      "introspection",
      "contemplation",
      "withdrawal",
      "solitude",
      "search for self",
    ],
    reversedPoints: [
      "loneliness",
      "isolation",
      "recluse",
      "being anti-social",
      "rejection",
      "returning to society",
    ],
  },
  {
    id: 68,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "Wheel of Fortune",
    uprightPoints: [
      "change",
      "cycles",
      "fate",
      "decisive moments",
      "luck",
      "fortune",
      "unexpected events",
    ],
    reversedPoints: [
      "bad luck",
      "lack of control",
      "clinging to control",
      "unwelcome changes",
      "delays",
    ],
  },
  {
    id: 69,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "Justice",
    uprightPoints: [
      "justice",
      "karma",
      "consequence",
      "accountability",
      "law",
      "truth",
      "honesty",
      "integrity",
      "cause and effect",
    ],
    reversedPoints: [
      "injustice",
      "retribution",
      "dishonesty",
      "corruption",
      "dishonesty",
      "unfairness",
      "avoiding accountability",
    ],
  },
  {
    id: 70,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "The Hanged Man",
    uprightPoints: [
      "sacrifice",
      "waiting",
      "uncertainty",
      "lack of direction",
      "perspective",
      "contemplation",
    ],
    reversedPoints: [
      "stalling",
      "disinterest",
      "stagnation",
      "avoiding sacrifice",
      "standstill",
      "apathy",
    ],
  },
  {
    id: 71,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "Death",
    uprightPoints: [
      "transformation",
      "endings",
      "change",
      "transition",
      "letting go",
      "release",
    ],
    reversedPoints: [
      "fear of change",
      "repeating negative patterns",
      "resisting change",
      "stagnancy",
      "decay",
    ],
  },
  {
    id: 72,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "Temperance",
    uprightPoints: [
      "balance",
      "peace",
      "patience",
      "moderation",
      "calm",
      "tranquillity",
      "harmony",
      "serenity",
    ],
    reversedPoints: [
      "imbalance",
      "excess",
      "extremes",
      "discord",
      "recklessness",
      "hastiness",
    ],
  },
  {
    id: 73,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "The Devil",
    uprightPoints: [
      "oppression",
      "addiction",
      "obsession",
      "dependency",
      "excess",
      "powerlessness",
      "limitations",
    ],
    reversedPoints: [
      "independence",
      "freedom",
      "revelation",
      "release",
      "reclaiming power",
      "reclaiming control",
    ],
  },
  {
    id: 74,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "The Tower",
    uprightPoints: [
      "disaster",
      "destruction",
      "upheaval",
      "trauma",
      "sudden change",
      "chaos",
    ],
    reversedPoints: [
      "averting disaster",
      "delaying the inevitable",
      "resisting change",
    ],
  },
  {
    id: 75,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "The Star",
    uprightPoints: [
      "hope",
      "inspiration",
      "positivity",
      "faith",
      "renewal",
      "healing",
      "rejuvenation",
    ],
    reversedPoints: [
      "hopelessness",
      "despair",
      "negativity",
      "lack of faith",
      "despondent",
    ],
  },
  {
    id: 76,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "The Moon",
    uprightPoints: [
      "illusion",
      "intuition",
      "uncertainty",
      "confusion",
      "complexity",
      "secrets",
      "unconscious",
    ],
    reversedPoints: [
      "fear",
      "deception",
      "anxiety",
      "misunderstanding",
      "misinterpretation",
      "clarity",
      "understanding",
    ],
  },
  {
    id: 77,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "The Sun",
    uprightPoints: [
      "happiness",
      "success",
      "optimism",
      "vitality",
      "joy",
      "confidence",
      "happiness",
      "truth",
    ],
    reversedPoints: [
      "blocked happiness",
      "excessive enthusiasm",
      "pessimism",
      "unrealistic expectations",
      "conceitedness",
    ],
  },
  {
    id: 78,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "Judgement",
    uprightPoints: [
      "self-evaluation",
      "awakening",
      "renewal",
      "purpose",
      "reflection",
      "reckoning",
    ],
    reversedPoints: [
      "self-doubt",
      "lack of self-awareness",
      "failure to learn lessons",
      "self-loathing",
    ],
  },
  {
    id: 79,
    cardType: "Major Arcana",
    cardCategory: "Major",
    cardName: "The World",
    uprightPoints: [
      "completion",
      "achievement",
      "fulfillment",
      "sense of belonging",
      "wholeness",
      "harmony",
    ],
    reversedPoints: [
      "lack of closure",
      "lack of achievement",
      "feeling incomplete",
      "emptiness",
    ],
  },
];
